@c "pair" "port" "-p, --port" "Port to use on" "21"
@c "pair" "host" "-h, --host" "Host to use on" "localhost"
@c "pair" "user" "-u, --user" "User to use on" "anonymous"
@c "pair" "pass" "-P, --password" "Password to use on" "password"
@c "pair" "user_agent" "-U, --user-agent" "User-Agent to use on" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.39"
